# Generated by Django 4.2 on 2023-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_historial_cardidhex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalregistrado',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
