# Generated by Django 4.2 on 2023-04-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardidevent',
            name='deviceID',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='postcardidevent',
            name='cardid',
            field=models.CharField(max_length=8),
        ),
    ]
